name: Build Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore --locked-mode

      # - name: Build
      #   run: dotnet build --configuration Release --no-restore

      # - name: Create the package
      #   run: dotnet pack --configuration Release src/CmdPalRandomDadJokeExtension

      # - name: Publish the package to GPR
      #   run: dotnet nuget push <my project>/bin/Release/*.nupkg